version: '3.7'

services:

 init:
  container_name: init
  build:
    context: ./
    dockerfile: services/server/dockerfiles/Dockerfile
  user: root
  volumes:
    - data:/cycshare_data/users
    - ./:/cycshare
    - ~/cycshare_backup/stats:/backup/stats
    - ~/cycshare_backup/users_data:/backup/users_data
    - ~/cycshare_backup/mariadb:/backup/mariadb:ro
  environment:
    - FLASK_ENV=init
    - RESTORE_DB=1
    - RESTORE_USERS_DATA=1
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - SECRET_KEY=${SECRET_KEY}
    - REDIS_ADDRESS=redis:6379/0
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    - MYSQL_USER=cycshare
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_HOST=mariadb
    - MYSQL_PORT=3306
    - ADMINS=cycshare@age.mpg.de
  links:
    - mariadb
  depends_on:
    - mariadb

 server:
  container_name: server
  ports:
    - 8887:8888 #jupyterhub
  build:
    context: ./
    dockerfile: services/server/dockerfiles/Dockerfile
  restart: always
  volumes:
   - ./utils/dev.py:/cycshare/cycshare/apps/external.py # this needs to be the first volume as otherwise it will be overwritten by `- ./:/cycshare`
   - data:/cycshare_data/users
   - ./:/cycshare
   - ~/cycshare_private:/cycshare_private:ro
  environment:
   - LOGS=/var/log/cycshare/
   - SECRET_KEY=${SECRET_KEY}
   - REDIS_ADDRESS=redis:6379/0
   - REDIS_PASSWORD=${REDIS_PASSWORD}
   - MAIL_USERNAME=cycshare@age.mpg.de
   - MYSQL_USER=cycshare
   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
   - MYSQL_HOST=mariadb
   - MYSQL_PORT=3306
   - FLASK_ENV=development
   - PRIVATE_APPS=/cycshare_private/private.apps.tsv
   - INSTANCE=(DEV)
   - ADMINS=cycshare@age.mpg.de
  links:
   - mariadb
   - redis
  depends_on:
   - init
   - mariadb
   - redis

 backup:
  container_name: backup
  image: flaski/backup:latest
  depends_on:
   - mariadb
   - init
  volumes:
   - ~/cycshare_backup/mariadb:/backup/mariadb
   - ~/cycshare_backup/users_data:/backup/users_data
   - data:/flaski_data/users:ro
  environment:
   - MYSQL_HOST=mariadb
   - MYSQL_USER=cycshare
   - MYSQL_PASS=${MYSQL_PASSWORD}
   - MAX_BACKUPS=15
   - INIT_BACKUP=0
   # Every day at 03:00
   - CRON_TIME=44 13 * * *
   #If set, restores latest backup
   #INIT_RESTORE_LATEST=yes
  restart: unless-stopped
  links:
   - mariadb

 mariadb:
  container_name: mariadb
  image: mariadb:10.5
  restart: always
  volumes:
   - db:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

 redis:
  container_name: redis
  image: redis:5
  restart: always
  command: redis-server --requirepass ${REDIS_PASSWORD}

 nginx:
  container_name: nginx
  image: nginx:alpine
  restart: always
  ports:
   - 80:80
   - 443:443
  volumes:
   - ./services/nginx/dev.conf:/etc/nginx/conf.d/default.conf:rw
   - ~/cycshare_data/certificates/cert.pem:/certs/cert.pem:ro 
   - ~/cycshare_data/certificates/key.pem:/certs/key.pem:ro
   - ~/cycshare_data/certificates/dhparam.pem:/certs/dhparam.pem:ro
  links:
   - server
  depends_on:
   - server

volumes:
 data:
  external: false
 db:
  external: false
