#!/bin/bash

set -e

if [ "${1}" == "nightly" ] ;
    then
        repoName="mpgagebioinformatics/myapp"
        IMAGE_NAME="myapp"
        DOCKER_TAG="nightly"
else
    # Parse image name for repo name
    tagStart=$(expr index "$IMAGE_NAME" :)
    repoName=${IMAGE_NAME:0:tagStart-1}
fi

echo ":: Repo: ${repoName}"
echo ":: Date: $(date '+%d/%m/%Y %H:%M:%S')"

cd ../../

if [ "${DOCKER_TAG}" == "latest" ] ;
    then 
        echo ":: Tag: ${DOCKER_TAG}"
        MYAPP_VERSION=$(git rev-parse --short HEAD)
        docker build --build-arg BUILD_NAME=myapp --build-arg MYAPP_VERSION=${MYAPP_VERSION} --no-cache -t ${repoName}:latest -f services/server/Dockerfile .
        docker push ${repoName}:latest && 
        echo ":: build & push tag: latest"

elif [ "${1}" == "nightly" ] ;
    then 

        MYAPP_VERSION=$(git rev-parse --short HEAD)
        echo ":: git #${MYAPP_VERSION}"
        text=":: !FAILED! "
        docker build --build-arg BUILD_NAME=myapp --build-arg MYAPP_VERSION="nightly-${MYAPP_VERSION}" --no-cache -t ${repoName}:nightly-${2} -f services/server/Dockerfile . && \
        text=":: "
        echo "${text}build myapp:nightly-${2}"

else
    echo ":: Tag: ${DOCKER_TAG}"
    docker build --build-arg BUILD_NAME=myapp --build-arg MYAPP_VERSION=${DOCKER_TAG} --no-cache -t ${repoName}:latest -f services/server/Dockerfile .
    docker tag ${repoName}:latest ${repoName}:${DOCKER_TAG}
    docker tag ${repoName}:latest ${repoName}:stable
    docker push ${repoName}:latest
    echo ":: push tag: latest"
    docker push ${repoName}:stable
    echo ":: push tag: stable"
    docker push ${repoName}:${DOCKER_TAG}
    echo ":: push tag: ${DOCKER_TAG}"

fi

echo ":: Finished"