#!/bin/bash

set -e

if [ "${1}" == "nightly" ] ||  [ "${1}" == "aarch64" ] ;
    then
        repoName="mpgagebioinformatics/myapp"
        IMAGE_NAME="myapp"
        DOCKER_TAG="nightly"
else
    # Parse image name for repo name
    tagStart=$(expr index "$IMAGE_NAME" :)
    repoName=${IMAGE_NAME:0:tagStart-1}
fi

echo ":: Building .."
echo ":: Repo: ${repoName}"
echo ":: Image: ${IMAGE_NAME}"
echo ":: Tag: ${DOCKER_TAG}"
echo ":: Date: $(date '+%d/%m/%Y %H:%M:%S')"

cd ../../

if [ "${DOCKER_TAG}" == "latest" ] ;
    then 
        MYAPP_VERSION=$(git rev-parse --short HEAD)
        docker build --build-arg MYAPP_VERSION=${MYAPP_VERSION} --no-cache -t ${repoName}:latest -f services/server/Dockerfile .
        docker tag ${repoName}:${DOCKER_TAG} ${repoName}:latest
        docker push ${repoName}:latest
        echo ":: push tag: latest"


elif [ "${1}" == "nightly" ] ;
    then 
        docker buildx create --use

        MYAPP_VERSION=$(git rev-parse --short HEAD)
        echo ":: git #${MYAPP_VERSION}"
        docker build --build-arg MYAPP_VERSION="nightly-${MYAPP_VERSION}" --no-cache -t ${repoName}:nightly -f services/server/Dockerfile . && \
        echo ":: build linux/amd64 myapp:nightly" && \
        docker push ${repoName}:nightly && \
        echo ":: push linux/amd64 myapp:nightly"
        docker buildx build --platform linux/arm64 --no-cache --build-arg MYAPP_VERSION="nightly-${MYAPP_VERSION}" -t ${repoName}:nightly -f services/server/Dockerfile . --push && \
        echo ":: build & push linux/arm64 myapp:nightly"
        
        docker build --no-cache -t mpgagebioinformatics/myapp-dockerize:nightly ./services/backup/ && \
        echo ":: build linux/amd64 myapp-dockerize:nightly" && \
        docker push mpgagebioinformatics/myapp-dockerize:nightly && \
        echo ":: push linux/amd64 myapp-dockerize:nightly"
        docker buildx build --platform linux/arm64 --no-cache -t mpgagebioinformatics/myapp-dockerize:nightly ./services/backup/ --push && \
        echo ":: build & push linux/arm64 myapp-dockerize:nightly"

elif [ "${1}" == "aarch64" ] ;
    then 
        MYAPP_VERSION=$(git rev-parse --short HEAD)
        echo ":: git #${MYAPP_VERSION}"
        docker build --build-arg MYAPP_VERSION="nightly-${MYAPP_VERSION}" --no-cache -t ${repoName}:nightly -f services/server/Dockerfile . && \
        echo ":: build linux/aarch64 myapp:nightly" && \
        docker push ${repoName}:nightly && \
        echo ":: push linux/aarch64 myapp:nightly"
        
        docker build --no-cache -t mpgagebioinformatics/myapp-dockerize:nightly ./services/backup/ && \
        echo ":: build linux/aarch64 myapp-dockerize:nightly" && \
        docker push mpgagebioinformatics/myapp-dockerize:nightly && \
        echo ":: push linux/aarch64 myapp-dockerize:nightly"

else
    cd ../../

    docker build --build-arg MYAPP_VERSION=${DOCKER_TAG} --no-cache -t ${repoName}:latest -f services/server/Dockerfile .
    docker tag ${repoName}:latest ${repoName}:${DOCKER_TAG}
    docker tag ${repoName}:latest ${repoName}:stable
    docker push ${repoName}:latest
    echo ":: push tag: latest"
    docker push ${repoName}:stable
    echo ":: push tag: stable"
    docker push ${repoName}:${DOCKER_TAG}
    echo ":: push tag: ${DOCKER_TAG}"

fi

echo ":: Finished"