#!/bin/bash

set -e

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

echo ":: Additional tagging"
echo ":: Repo: ${repoName}"
echo ":: Image: ${IMAGE_NAME}"
echo ":: Tag: ${DOCKER_TAG}"


# Tag and push image for each additional tag
if [ "${DOCKER_TAG}" == "latest" ] ; then
    if [ $(git describe --abbrev=0 --tags) ] ; 
        then 
            tag=$(git describe --abbrev=0 --tags)
            docker tag $IMAGE_NAME ${repoName}:${tag}-latest
            docker push ${repoName}:${tag}-latest
            echo ":: Added tag: ${tag}-latest"
    fi
elif [ "${DOCKER_TAG}" == "nightly" ] ;
    if [ $(git describe --abbrev=0 --tags) ] ; 
        then 
            tag=$(git describe --abbrev=0 --tags)
            docker tag $IMAGE_NAME ${repoName}:${tag}-nightly
            docker push ${repoName}:${tag}-nightly
            docker tag $IMAGE_NAME ${repoName}:latest
            docker push ${repoName}:latest
            echo ":: Added tag: ${tag}-nightly"
            echo ":: Added tag: latest"
    fi
else ;
    if [ $(git describe --abbrev=0 --tags) ] ; 
        then 
            tag=$(git describe --abbrev=0 --tags)
            docker tag $IMAGE_NAME ${repoName}:latest
            docker push ${repoName}:latest
            echo ":: Added tag: latest"
    fi
fi