#!/bin/bash

set -e

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

echo ":: Additional tagging"
echo ":: Repo: ${repoName}"
echo ":: Image: ${IMAGE_NAME}"
echo ":: Tag: ${DOCKER_TAG}"


if [ "${DOCKER_TAG}" != "latest" ] ;
    then 
        docker tag ${repoName}:${DOCKER_TAG} ${repoName}:latest
        docker push ${repoName}:latest
        echo ":: Added tag: latest"
        docker tag ${repoName}:${DOCKER_TAG} ${repoName}:stable
        docker push ${repoName}:stable
        echo ":: Added tag: stable"
fi
echo ":: Finished"

# cd ../../

# Tag and push image for each additional tag
# if [ "${DOCKER_TAG}" == "latest" ] ; 
#     then
#         if [ $(git describe --abbrev=0 --tags) ] ; 
#             then 
#                 tag=$(git describe --abbrev=0 --tags)
#                 docker tag mpgagebioinformatics/myapp:${DOCKER_TAG} mpgagebioinformatics/myapp:${tag}-latest
#                 docker push mpgagebioinformatics/myapp:${tag}-latest
#                 echo ":: Added tag: ${tag}-latest"
#         fi
# 
        # CURRENTLY BUILDS ON OTHER PLATFORMS ARE FAILING ON THE HUB 
        # docker buildx create --name mybuilder
        # docker buildx use mybuilder
        # for platform in linux/arm64 linux/arm/v7 ;
        #     do
        #         echo ":: Building ${platform} tag: ${DOCKER_TAG}"
        #         docker buildx build --platform ${platform} --no-cache -t mpgagebioinformatics/myapp:${DOCKER_TAG} -f services/server/Dockerfile . --push
        #         if [ $(git describe --abbrev=0 --tags) ] ;
        #             then 
        #                 ":: Building ${platform} tag: ${tag}-latest"
        #                 docker buildx build --platform  ${platform} -t mpgagebioinformatics/myapp:${tag}-latest -f services/server/Dockerfile . --push
        #         fi
        # done

# elif [ "${DOCKER_TAG}" == "nightly" ] ;
#     then
#         if [ $(git describe --abbrev=0 --tags) ] ; 
#             then 
#                 tag=$(git describe --abbrev=0 --tags)
#                 docker tag mpgagebioinformatics/myapp:${DOCKER_TAG} mpgagebioinformatics/myapp:${tag}-nightly
#                 docker push mpgagebioinformatics/myapp:${tag}-nightly
#                 echo ":: Added tag: ${tag}-nightly"
#         fi
#         docker tag mpgagebioinformatics/myapp:${DOCKER_TAG} mpgagebioinformatics/myapp:latest
#         docker push mpgagebioinformatics/myapp:latest
#         echo ":: Added tag: latest"
        
        # CURRENTLY BUILDS ON OTHER PLATFORMS ARE FAILING ON THE HUB 
        # docker buildx create --name mybuilder
        # docker buildx use mybuilder
        # for platform in linux/arm64 linux/arm/v7 ;
        #     do
        #         echo ":: Building ${platform} tag: nightly"
        #         docker buildx build --platform ${platform} --no-cache -t mpgagebioinformatics/myapp:nightly -f services/server/Dockerfile . --push
        #         if [ $(git describe --abbrev=0 --tags) ] ;
        #             then 
        #                 ":: Building ${platform} tag: ${tag}-latest"
        #                 docker buildx build --platform  ${platform} -t mpgagebioinformatics/myapp:${tag}-nightly -f services/server/Dockerfile . --push
        #         fi
        #         echo ":: Building ${platform} tag: latest"
        #         docker buildx build --platform ${platform} -t mpgagebioinformatics/myapp:latest -f services/server/Dockerfile . --push
        # done

# else
#     docker tag mpgagebioinformatics/myapp:${DOCKER_TAG} mpgagebioinformatics/myapp:latest
#     docker push mpgagebioinformatics/myapp:latest
#     echo ":: Added tag: latest"

#     # docker buildx create --name mybuilder
#     # docker buildx use mybuilder
#     # for platform in linux/arm64 linux/arm/v7 ;
#     #     do
#     #         echo ":: Building ${platform} tag: ${DOCKER_TAG}"
#     #         docker buildx build --platform ${platform} --no-cache -t mpgagebioinformatics/myapp:${DOCKER_TAG} -f services/server/Dockerfile . --push
#     #         echo ":: Building ${platform} tag: latest"
#     #         docker buildx build --platform ${platform} -t mpgagebioinformatics/myapp:latest -f services/server/Dockerfile . --push
#     # done

#     cd serivces/backup
    
#     echo ":: Building myapp-dockerize"
#     docker build -t mpgagebioinformatics/myapp-dockerize:${DOCKER_TAG} .
#     docker tag mpgagebioinformatics/myapp-dockerize:${DOCKER_TAG} mpgagebioinformatics/myapp-dockerize:latest
#     docker push mpgagebioinformatics/myapp-dockerize:${DOCKER_TAG}
#     docker push mpgagebioinformatics/myapp-dockerize:latest

    # docker push mpgagebioinformatics/myapp-dockerize:latest
    # docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t mpgagebioinformatics/myapp-dockerize:latest . --push
    # echo ":: Building myapp-dockerize:${DOCKER_TAG}"
    # docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t mpgagebioinformatics/myapp-dockerize:${DOCKER_TAG} . --push

# fi

# echo ":: Finished"