apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    type: local # gcePersistentDisk / local
spec:
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/jboucas/myapp_pv/db"

# types of volumes: https://kubernetes.io/docs/concepts/storage/volumes