apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bc-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: bc-pv
  storageClassName: standard