apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: db-pvc
#   labels:
#     type: local
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   volumeName: db-pv
#   storageClassName: standard