apiVersion: v1
kind: Pod
metadata:
  name: rsync
  labels:
    app: rsync
spec:
  containers:
  - image: mpgagebioinformatics/myapp:latest #hub.age.mpg.de/flaski/server
    imagePullPolicy: Always
    name: init
    command: ["tail", "-f", "/dev/null"]
    env:
    - name: APP_NAME
      value: myapp
    - name: APP_TITLE
      value: myapp
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: myapp-secrets
          key: SECRET_KEY
    - name: FLASK_ENV
      value: init
    - name: RESTORE_DB
      value: "1"
    - name: RESTORE_USERS_DATA
      value: "0"
    - name: MAIL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: gmailpass
          key: pass
    - name: MYSQL_HOST
      value: mariadb
    - name: MYSQL_PORT
      value: "3306"
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: myapp-secrets
          key: MYSQL_ROOT_PASSWORD
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: myapp-secrets
          key: MYSQL_PASSWORD
    - name: MYSQL_USER
      value: myapp
    - name: REDIS_ADDRESS
      value: redis:6379/0
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: myapp-secrets
          key: REDIS_PASSWORD
    - name: ADMINS
      value: jboucas@gmail.com
    resources: {}
    volumeMounts:
    - name: backup-volume-mount
      mountPath: /backup      
  restartPolicy: Always
  imagePullSecrets:
    - name: dockerlogin
  volumes:
  - name: backup-volume-mount
    persistentVolumeClaim:
      claimName: bc-pvc

status: {}
