apiVersion: v1
kind: Secret
metadata:
  name: myapp-secrets
type: Opaque
stringData:
    SECRET_KEY: SECRET_KEY
    MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
    REDIS_PASSWORD: REDIS_PASSWORD
    MYSQL_PASSWORD: MYSQL_PASSWORD