apiVersion: v1
kind: Secret
metadata:
  name: myapp-secrets
type: Opaque
stringData:
    SECRET_KEY: 4QHb2xw13jSZQDHayq1tsBtYpRc=
    MYSQL_ROOT_PASSWORD: gezmaowTrenNNbw7NnyQ0MStB4g=
    REDIS_PASSWORD: hWZx9h9JagVKJwAIuVE8PGzurcE=
    MYSQL_PASSWORD: YTO+XWQvmn0CIDzMPL2pUpUKwMI=