apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: users-pv
  storageClassName: standard