name: tag

on:
  push:
    tags: [ '*.*.*' ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        MYAPP_VERSION=${GITHUB_REF#refs/*/}
        git clone https://github.com/mpg-age-bioinformatics/flaski.git ${MYAPP_VERSION}
        cd ${MYAPP_VERSION}
        git checkout ${MYAPP_VERSION}
        docker buildx create --name mybuilder --driver docker-container --bootstrap --use
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx build --platform linux/amd64,linux/arm64 --build-arg BUILD_NAME=myapp --build-arg MYAPP_VERSION=${MYAPP_VERSION} --no-cache -t docker.io/mpgagebioinformatics/myapp:latest -t docker.io/mpgagebioinformatics/myapp:${MYAPP_VERSION} -f services/server/Dockerfile --push .
  
  # docker build . --tag docker.io/mpgagebioinformatics/flaski:dev
  # docker push docker.io/mpgagebioinformatics/flaski:dev


  slackNotification:
    needs: build
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: github_action_bot
        SLACK_CHANNEL: flaski
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: "[myapp] ${GITHUB_REF#refs/*/} build and push completed"

